# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'bugsnag-example' do
	pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"
end

target 'bugsnag-exampleTests' do

end

