language: objective-c
cache:
- bundler
- cocoapods

install: make bootstrap

env:
- TEST_CONFIGURATION=Debug

script: make analyze test

stages:
- build
- macOS unit tests
- unit tests
- integration
- name: deploy
  if: branch = master AND tag IS present

jobs:
  include:

  # ----------------------------------------------------------------------------
  # Unit Tests - Mac
  # ----------------------------------------------------------------------------

  - osx_image: xcode12.2 # macos 10.15.7
    name: macOS 10.15.7 unit tests
    stage: macOS unit tests
    env: PLATFORM=macOS

  - osx_image: xcode11.6 # macos 10.15.5
    name: macOS 10.15.5 unit tests
    stage: macOS unit tests
    env: PLATFORM=macOS

  - osx_image: xcode10.2 # macos 10.14
    name: macOS 10.14 unit tests
    stage: macOS unit tests
    env: PLATFORM=macOS

  - osx_image: xcode9.4 # macos 10.13
    name: macOS 10.13 unit tests
    stage: macOS unit tests
    env: PLATFORM=macOS
  
  # ----------------------------------------------------------------------------
  # Unit Tests - iOS
  # ----------------------------------------------------------------------------

  - osx_image: xcode12.2
    name: iOS 11-14 unit tests
    stage: unit tests
    env:
    - PLATFORM=iOS
    - DEVICE="iPhone 8"
    script:
    - make test OS=14.1
    - make test OS=13.5
    - make test OS=12.4
    - make test OS=11.4

  - osx_image: xcode11
    name: iOS 10 unit tests
    stage: unit tests
    env:
    - PLATFORM=iOS
    - DEVICE="iPhone 7"
    script:
    - make test OS=10.3.1

  - osx_image: xcode10.2
    name: iOS 9 unit tests
    stage: unit tests
    env: PLATFORM=iOS
    before_script:
    # https://stackoverflow.com/questions/55389080/xcode-10-2-failed-to-run-app-on-simulator-with-ios-10
    - sudo mkdir -p '/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift'
    script:
    - make test OS=9.3
    - make test OS=9.3 TEST_CONFIGURATION=Release

  # ----------------------------------------------------------------------------
  # Unit Tests - tvOS
  # ----------------------------------------------------------------------------

  - osx_image: xcode12.2
    name: tvOS 11-14 unit tests
    stage: unit tests
    env: PLATFORM=tvOS
    script:
    - make test OS=14.0
    - make test OS=13.3
    - make test OS=12.4
    - make test OS=11.4
    
  - osx_image: xcode11
    name: tvOS 10 unit tests
    stage: unit tests
    env: PLATFORM=tvOS
    script:
    - make test OS=10.2

  - osx_image: xcode10.2
    name: tvOS 9 unit tests
    stage: unit tests
    env: PLATFORM=tvOS
    script:
    - make test OS=9.2

  # ----------------------------------------------------------------------------
  # Static framework, Carthage and Swift Package Manager builds
  # ----------------------------------------------------------------------------
    
  - osx_image: xcode11
    name: Static framework, Carthage and Swift Package Manager builds
    stage: integration
    before_script:
      # Xcode 11+ no longer ships with all device combinations premade
    - xcrun simctl create "13-xs" "iPhone XS" com.apple.CoreSimulator.SimRuntime.iOS-13-0
    - mkdir -p features/fixtures/carthage-proj
    script:
    - make build_swift      # Build with Swift Package Manager
    - make build_carthage   # Build example carthage project
    - make build_ios_static # Build static framework target

  # ----------------------------------------------------------------------------
  # Doc Generation
  # ----------------------------------------------------------------------------

  - osx_image: xcode11
    stage: deploy
    before_deploy: make doc
    script: skip
    deploy:
      provider: pages
      local_dir: docs # only include the contents of the generated docs dir
      skip_cleanup: true
      github_token: $GITHUB_TOKEN # set in travis-ci dashboard
      on:
        tags: true # only deploy when tag is applied to commit
