steps:
  - label: Build cocoa IPA
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa
    artifact_paths:
      - features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - wait

  - label: ':ios: iOS 14 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
    concurrency: 10
    concurrency_group: browserstack-app

  - label: ':ios: iOS 13 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_13"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
    concurrency: 10
    concurrency_group: browserstack-app

  - label: ':ios: iOS 12 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_12"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
    concurrency: 10
    concurrency_group: browserstack-app

  - label: ':ios: iOS 11 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
    concurrency: 10
    concurrency_group: browserstack-app

  - label: ':ios: iOS 10 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--username=$BROWSER_STACK_USERNAME"
          - "--access-key=$BROWSER_STACK_ACCESS_KEY"
    concurrency: 10
    concurrency_group: browserstack-app
