steps:
  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa
    artifact_paths:
      - features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - label: macOS 10.15 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
    commands:
      - make bootstrap
      - PLATFORM=macOS make analyze test

  - label: Static framework, Carthage and Swift Package Manager builds
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
    commands:
      - make bootstrap
      - xcrun simctl create "13-xs" "iPhone XS" com.apple.CoreSimulator.SimRuntime.iOS-13-0
      - mkdir -p features/fixtures/carthage-proj
      - make build_swift
      - make build_carthage
      - make build_ios_static

  - label: xcode12+ unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
    commands:
      - make bootstrap
      - PLATFORM=iOS make test OS=14.1
      - PLATFORM=tvOS make test OS=14.0
      - PLATFORM=macOS make analyze test

  - label: xcode11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
    commands:
      - make bootstrap
      - PLATFORM=iOS DEVICE="iPhone 7" make test OS=10.3.1
      - PLATFORM=tvOS make test OS=10.2
      - PLATFORM=macOS make analyze test

  - label: xcode10.2 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    env:
      LANG: "en_GB.UTF-8"
    commands:
      - sudo mkdir -p '/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift'
      - make bootstrap
      - TEST_CONFIGURATION=Debug PLATFORM=iOS make test OS=9.3
      - TEST_CONFIGURATION=Release PLATFORM=iOS make test OS=9.3
      - TEST_CONFIGURATION=Debug PLATFORM=tvOS make test OS=9.2
      - TEST_CONFIGURATION=Debug PLATFORM=macOS make analyze test

  - label: iOS 11-13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
    commands:
      - make bootstrap
      - PLATFORM=iOS make test OS=13.7
      - PLATFORM=iOS make test OS=12.4
      - PLATFORM=iOS make test OS=11.4

  - label: tvOS 11-13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
    commands:
      - make bootstrap
      - PLATFORM=tvOS make test OS=13.3
      - PLATFORM=tvOS make test OS=12.4
      - PLATFORM=tvOS make test OS=11.4

  # - label: ':ios: iOS 14 end-to-end tests'
  #   depends_on:
  #     - cocoa_fixture
  #   timeout_in_minutes: 60
  #   agents:
  #     queue: opensource
  #   plugins:
  #     artifacts#v1.3.0:
  #       download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
  #     docker-compose#v3.3.0:
  #       run: cocoa-maze-runner
  #       command:
  #         - "--app=/app/build/iOSTestApp.ipa"
  #         - "--farm=bs"
  #         - "--device=IOS_14"
  #         - "--resilient"
  #         - "--appium-version=1.17.0"
  #         - "--fail-fast"
  #   concurrency: 9
  #   concurrency_group: browserstack-app
  #   retry:
  #     automatic:
  #       - exit_status: -1  # Agent was lost
  #         limit: 2

  # - label: ':ios: iOS 13 end-to-end tests'
  #   depends_on:
  #     - cocoa_fixture
  #   timeout_in_minutes: 60
  #   agents:
  #     queue: opensource
  #   plugins:
  #     artifacts#v1.3.0:
  #       download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
  #     docker-compose#v3.3.0:
  #       run: cocoa-maze-runner
  #       command:
  #         - "--app=/app/build/iOSTestApp.ipa"
  #         - "--farm=bs"
  #         - "--device=IOS_13"
  #         - "--resilient"
  #         - "--appium-version=1.17.0"
  #         - "--fail-fast"
  #   concurrency: 9
  #   concurrency_group: browserstack-app
  #   retry:
  #     automatic:
  #       - exit_status: -1  # Agent was lost
  #         limit: 2

  # - label: ':ios: iOS 12 end-to-end tests'
  #   depends_on:
  #     - cocoa_fixture
  #   timeout_in_minutes: 60
  #   agents:
  #     queue: opensource
  #   plugins:
  #     artifacts#v1.3.0:
  #       download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
  #     docker-compose#v3.3.0:
  #       run: cocoa-maze-runner
  #       command:
  #         - "--app=/app/build/iOSTestApp.ipa"
  #         - "--farm=bs"
  #         - "--device=IOS_12"
  #         - "--resilient"
  #         - "--appium-version=1.17.0"
  #         - "--fail-fast"
  #   concurrency: 9
  #   concurrency_group: browserstack-app
  #   retry:
  #     automatic:
  #       - exit_status: -1  # Agent was lost
  #         limit: 2

  # - label: ':ios: iOS 11 end-to-end tests'
  #   depends_on:
  #     - cocoa_fixture
  #   # More time than other steps as the BrowserStack iOS 11 devices seem particularly unstable and
  #   # sessions need resetting frequently, taking a minute or more each time.
  #   timeout_in_minutes: 90
  #   agents:
  #     queue: opensource
  #   plugins:
  #     artifacts#v1.3.0:
  #       download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
  #     docker-compose#v3.3.0:
  #       run: cocoa-maze-runner
  #       command:
  #         - "--app=/app/build/iOSTestApp.ipa"
  #         - "--farm=bs"
  #         - "--device=IOS_11_0_IPHONE_8_PLUS"
  #         - "--resilient"
  #         - "--appium-version=1.16.0"
  #         - "--fail-fast"
  #   concurrency: 9
  #   concurrency_group: browserstack-app
  #   retry:
  #     automatic:
  #       - exit_status: -1  # Agent was lost
  #         limit: 2

  # - label: ':ios: iOS 10 end-to-end tests'
  #   depends_on:
  #     - cocoa_fixture
  #   timeout_in_minutes: 60
  #   agents:
  #     queue: opensource
  #   plugins:
  #     artifacts#v1.3.0:
  #       download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
  #     docker-compose#v3.3.0:
  #       run: cocoa-maze-runner
  #       command:
  #         - "--app=/app/build/iOSTestApp.ipa"
  #         - "--farm=bs"
  #         - "--device=IOS_10"
  #         - "--resilient"
  #         - "--appium-version=1.15.0"
  #         - "--fail-fast"
  #   concurrency: 9
  #   concurrency_group: browserstack-app
  #   retry:
  #     automatic:
  #       - exit_status: -1  # Agent was lost
  #         limit: 2
