env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
      - features/fixtures/ios/output/ipa_url_bb.txt
      - features/fixtures/ios/output/ipa_url_bs.txt
    commands:
      - bundle install
      - make test-fixtures
      - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/iOSTestApp.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bb.txt
      - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/iOSTestApp.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bs.txt

  - label: Static framework and Swift Package Manager builds
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - make build_swift
      - make build_ios_static

  - label: Carthage
    timeout_in_minutes: 15
    agents:
      queue: macos-12-arm
    commands:
      - ./scripts/build-carthage.sh
    plugins:
      artifacts#v1.5.0:
        upload: "features/fixtures/carthage/carthage-*.log"

  ##############################################################################
  #
  # Unit tests
  #

  - label: ARM macOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-11
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 10.15 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-10.15
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 10.14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 10.13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: iOS 15 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=15.0
    artifact_paths:
      - logs/*

  - label: iOS 14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=14.5
    artifact_paths:
      - logs/*

  - label: iOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-11
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=11.4
    artifact_paths:
      - logs/*

  - label: iOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-10.15
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=10.3.1 DEVICE=iPhone\ 5s
    artifact_paths:
      - logs/*

  - label: iOS 9 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=9.0 DEVICE=iPhone\ 5s
    artifact_paths:
      - logs/*

  - label: tvOS 15 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=15.0
    artifact_paths:
      - logs/*

  - label: tvOS 14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=14.5
    artifact_paths:
      - logs/*

  - label: tvOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-11
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=11.4
    artifact_paths:
      - logs/*

  - label: tvOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-10.15
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=10.2
    artifact_paths:
      - logs/*

  - label: tvOS 9 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=9.2
    artifact_paths:
      - logs/*

  - label: watchOS 8 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    env:
      DEVELOPER_DIR: /Applications/Xcode13.4.app
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=watchOS OS=8.3
    artifact_paths:
      - logs/*

  - label: watchOS 7 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    env:
      DEVELOPER_DIR: /Applications/Xcode13.4.app
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=watchOS OS=7.4
    artifact_paths:
      - logs/*

  - label: 'macOS 10.13 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --os=macos
        --fail-fast
        --order=random

  - label: 'macOS 10.15 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: macos-10.15
    plugins:
      artifacts#v1.5.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "maze_output/failed/**/*"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --os=macos
        --fail-fast
        --order=random

  - label: 'ARM macOS 12 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: macos-12-arm
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        --os=macos
        --fail-fast
        --order=random

  - label: 'macOS 12 stress test'
    timeout_in_minutes: 3
    agents:
      queue: macos-12-arm
    env:
      STRESS_TEST: "true"
    commands:
      - echo "--- Bundle install"
      - bundle install
      - echo "--- Build"
      - make -C features/fixtures/macos-stress-test
      - echo "--- Test"
      - bundle exec maze-runner
        features/stress_test.feature
        --no-log-requests
    artifact_paths:
      - features/fixtures/macos-stress-test/*.log
      - features/fixtures/macos-stress-test/*.crash

  ##############################################################################
  #
  # Basic build E2E tests
  #

  #
  # BitBar
  #
  - label: ':bitbar: iOS 16 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_16"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
          - "--order=random"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 16 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_16"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[a-d].*.feature$"
          - "--order=random"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 15 barebone tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "features/barebone_tests.feature"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 14 barebone tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_14"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "features/barebone_tests.feature"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 13 barebone tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "features/barebone_tests.feature"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 12 barebone tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_12"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "features/barebone_tests.feature"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  #
  # BrowserStack
  #
  - label: ':browserstack: iOS 11 barebone tests'
    skip: "https://smartbear.atlassian.net/browse/PLAT-11154"
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url_bs.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url_bs.txt"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_8_PLUS"
          - "--appium-version=1.16.0"
          - "features/barebone_tests.feature"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':browserstack: iOS 10 barebone tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url_bs.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url_bs.txt"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.15.0"
          - "--fail-fast"
          - "features/barebone_tests.feature"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  ##############################################################################
  #
  # Trigger more tests
  #

  - label: 'Conditionally trigger full set of tests'
    command: sh -c .buildkite/pipeline_trigger.sh
