steps:
  - label: macOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "macOS"
    commands:
      - make bootstrap
      - make analyze test

  - label: macOS 10.14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "macOS"
    commands:
      - make bootstrap
      - make analyze test

  - label: iOS 13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "13.7"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: iOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "12.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: iOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "11.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: iOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "iOS"
      OS: "10.3.1"
      DEVICE: "iPhone 5s"
    commands:
      - make bootstrap
      - make test

  - label: tvOS 13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "13.3"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: tvOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "12.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: tvOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "11.4"
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make bootstrap
      - make test

  - label: tvOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    env:
      LANG: "en_GB.UTF-8"
      TEST_CONFIGURATION: "Debug"
      PLATFORM: "tvOS"
      OS: "10.2"
    commands:
      - make bootstrap
      - make test

  - label: ':apple: macOS 10.15 full end-to-end tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=10.15
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast

  - label: ':ios: iOS 14 full end-to-end tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--resilient"
          - "--appium-version=1.17.0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':ios: iOS 10 full end-to-end tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 120
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--resilient"
          - "--appium-version=1.15.0"
          - "--fail-fast"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
