env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Unit tests
  #

  - label: ARM macOS 14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-14-multiagent
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: iOS 17 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-14-multiagent
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=17.0.1 DEVICE="iPhone 15"
    env:
      XCODE_VERSION: 15.3.0
    artifact_paths:
      - logs/*

  - label: watchOS 8 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-14-multiagent
    env:
      XCODE_VERSION: 15.3.0
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=watchOS OS=8.5 SDK=watchsimulator10.4
    artifact_paths:
      - logs/*

  - label: iOS 17 unit tests
    timeout_in_minutes: 10
    agents:
      queue: macos-14-multiagent
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=17.0.1 DEVICE="iPhone 15"
    env:
      XCODE_VERSION: 15.3.0
    artifact_paths:
      - logs/*