env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #
  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 15
    agents:
      queue: macos-15
    env:
      XCODE_VERSION: 16.3.0
    commands:
      - bundle install
      - make test-fixtures

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 15
    agents:
      queue: macos-15
    env:
      XCODE_VERSION: 16.3.0
    commands:
      - bundle install
      - make test-fixtures

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 15
    agents:
      queue: macos-15
    env:
      XCODE_VERSION: 16.3.0
    commands:
      - bundle install
      - make test-fixtures

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 15
    agents:
      queue: macos-15
    env:
      XCODE_VERSION: 16.3.0
    commands:
      - bundle install
      - make test-fixtures

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 15
    agents:
      queue: macos-15
    env:
      XCODE_VERSION: 16.3.0
    commands:
      - bundle install
      - make test-fixtures
