agents:
  queue: opensource
env:
  LANG: "en_GB.UTF-8"

steps:

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 15
    agents:
      queue: macos-15
    env:
      XCODE_VERSION: 16.3.0
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp_Release.ipa
      - features/fixtures/ios/output/ipa_url_bs_release.txt
    commands:
      - ruby scripts/build-test-fixture.rb

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':browserstack: iOS 18'
    depends_on: cocoa_fixture
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.4:
        download:
          - "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload:
          - "maze_output/failed/**/*"
          - "maze_output/maze_output.zip"
      docker-compose#v5.8.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@features/fixtures/ios/output/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_18"
          - "--appium-version=1.21.0"
          - "features/release/breadcrumbs.feature:45"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

