env:
  LANG: "en_GB.UTF-8"

steps:
  - label: 'Trigger RN tests for all builds of our next branch'
    if: build.branch == "next"
    trigger: 'bugsnag-js'
    build:
      branch: 'next'
      message: 'Run RN tests with latest Cocoa next branch'
      env:
        BUILD_RN_WITH_LATEST_NATIVES: "true"
    async: true

  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 30
    agents:
      queue: opensource-arm-mac-cocoa-12
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
      - features/fixtures/ios/output/ipa_url.txt
    commands:
      - ./features/scripts/build_and_upload_app.rb

  - label: Static framework and Swift Package Manager builds
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - make build_swift
      - make build_ios_static

  - label: Carthage
    timeout_in_minutes: 15
    agents:
      queue: opensource-arm-mac-cocoa-12
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/build-carthage.sh
    plugins:
      artifacts#v1.3.0:
        upload: "features/fixtures/carthage/carthage-*.log"

  ##############################################################################
  #
  # Unit tests
  #

  - label: ARM macOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 10.15 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.15
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 10.13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: iOS 14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=14.5
    artifact_paths:
      - logs/*

  - label: iOS 9 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=9.3 DEVICE=iPhone\ 5s XCODEBUILD_EXTRA_ARGS=-skip-testing:BugsnagNetworkRequestPlugin-iOSTests
    artifact_paths:
      - logs/*

  - label: tvOS 14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=14.5
    artifact_paths:
      - logs/*

  - label: tvOS 9 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=9.2 XCODEBUILD_EXTRA_ARGS=-skip-testing:BugsnagNetworkRequestPlugin-tvOSTests
    artifact_paths:
      - logs/*

  ##############################################################################
  #
  # Barebones E2E tests
  #

  - label: 'iOS 15 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "features/barebone_tests.feature"
          - "features/app_hangs.feature"
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_15"
          - "--appium-version=1.21.0"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "features/barebone_tests.feature"
          - "features/app_hangs.feature"
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
          - "--capabilities={\"browserstack.networkLogs\":\"true\"}"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'macOS 10.13 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.13
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        features/app_hangs.feature
        --farm=local
        --os=macos
        --os-version=10.13
        --app=macOSTestApp
        --fail-fast
        --order=random

  - label: 'macOS 10.15 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.15
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        features/app_hangs.feature
        --farm=local
        --os=macos
        --os-version=10.15
        --app=macOSTestApp
        --fail-fast
        --order=random

  - label: 'ARM macOS 12 barebones E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    plugins:
      artifacts#v1.3.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "appium_server.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle config set --local path 'vendor/bundle'
      - bundle install
      - bundle exec maze-runner
        features/barebone_tests.feature
        features/app_hangs.feature
        --farm=local
        --os=macos
        --os-version=12
        --app=macOSTestApp
        --order=random

  - label: 'macOS 12 stress test'
    timeout_in_minutes: 3
    agents:
      queue: opensource-arm-mac-cocoa-12
    env:
      STRESS_TEST: "true"
    commands:
      - echo "--- Bundle install"
      - bundle install
      - echo "--- Build"
      - make -C features/fixtures/macos-stress-test
      - echo "--- Test"
      - bundle exec maze-runner
        features/stress_test.feature
        --no-log-requests
    artifact_paths:
      - features/fixtures/macos-stress-test/*.log
      - features/fixtures/macos-stress-test/*.crash

  ##############################################################################
  #
  # Trigger more tests
  #

  - label: 'Conditionally trigger full set of tests'
    command: sh -c .buildkite/pipeline_trigger.sh
