env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: iOS 14 unit tests default
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-1
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=14.5
    artifact_paths:
      - logs/*

  - label: iOS 14 unit tests 13
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-1
    env:
      XCODE_VERSION: "13.2.1"
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=14.5
    artifact_paths:
      - logs/*

  - label: iOS 14 unit tests 14
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-1
    env:
      XCODE_VERSION: "14.1.0"
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=14.5
    artifact_paths:
      - logs/*

  - label: tvOS 14 unit tests default
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-1
    env:
      XCODE_VERSION: "13.2.1"
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=14.5
    artifact_paths:
      - logs/*

  - label: tvOS 14 unit tests 13
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-1
    env:
      XCODE_VERSION: "13.2.1"
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=14.5
    artifact_paths:
      - logs/*

  - label: tvOS 14 unit tests 14
    timeout_in_minutes: 10
    agents:
      queue: ms-arm-12-1
    env:
      XCODE_VERSION: "14.1.0"
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=14.5
    artifact_paths:
      - logs/*

