env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # E2E tests
  #

  - label: 'iOS 13 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_13"
          - "--resilient"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[h-z].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 13 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_13"
          - "--resilient"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[a-g].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 12 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_12"
          - "--resilient"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[h-z].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 12 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_12"
          - "--resilient"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[a-g].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 11 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    # More time than other steps as the BrowserStack iOS 11 devices seem particularly unstable and
    # sessions need resetting frequently, taking a minute or more each time.
    timeout_in_minutes: 50
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_8_PLUS"
          - "--appium-version=1.8.0"
          - "--fail-fast"
          - "--exclude=features/[h-z].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 11 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    # More time than other steps as the BrowserStack iOS 11 devices seem particularly unstable and
    # sessions need resetting frequently, taking a minute or more each time.
    timeout_in_minutes: 50
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_8_PLUS"
          - "--appium-version=1.8.0"
          - "--fail-fast"
          - "--exclude=features/[a-g].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'macOS 11.0 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa-11
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "appium_server.log"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=11.0
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        --order=random

  - label: 'macOS 10.13 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa-10.13
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "appium_server.log"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=10.13
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        --order=random

  - label: 'macOS 10.14 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa-10.14
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "appium_server.log"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=10.14
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        --order=random

  ##############################################################################
  #
  # Build example apps
  #

  - label: 'examples/objective-c-ios'
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - cd examples/objective-c-ios
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -workspace Bugsnag\ Test\ App.xcworkspace -scheme Bugsnag\ Test\ App -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -workspace Bugsnag\ Test\ App.xcworkspace -scheme Bugsnag\ Test\ App -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/objective-c-osx'
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - cd examples/objective-c-osx
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Release -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Debug -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swift-ios'
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - cd examples/swift-ios
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -workspace bugsnag-example.xcworkspace -scheme bugsnag-example -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -workspace bugsnag-example.xcworkspace -scheme bugsnag-example -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swift-package-manager'
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - cd examples/swift-package-manager
      - echo "--- Resolve Swift Package Dependencies"
      - sed -i '' -e 's/kind = branch/kind = revision/' -e "s/branch = master/revision = ${BUILDKITE_COMMIT}/" swift-package-manager.xcodeproj/project.pbxproj
      - xcodebuild -scheme swift-package-manager -derivedDataPath DerivedData -resolvePackageDependencies
      - echo "+++ Build Release iOS"
      - xcodebuild -scheme swift-package-manager -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -scheme swift-package-manager -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
