env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Unit tests
  #

  - label: macOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 10.14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: iOS 13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=13.7
    artifact_paths:
      - logs/*

  - label: iOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=12.4
    artifact_paths:
      - logs/*

  - label: iOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=11.4
    artifact_paths:
      - logs/*

  - label: iOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.15
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=10.3.1 DEVICE=iPhone\ 5s
    artifact_paths:
      - logs/*

  - label: tvOS 13 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=13.4
    artifact_paths:
      - logs/*

  - label: tvOS 12 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=12.4
    artifact_paths:
      - logs/*

  - label: tvOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    concurrency: 3
    concurrency_group: cocoa-unit-tests
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=11.4
    artifact_paths:
      - logs/*

  - label: tvOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.15
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=10.2
    artifact_paths:
      - logs/*

  ##############################################################################
  #
  # E2E tests
  #

  - label: 'macOS 10.15 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa-10.15
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "appium_server.log"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=10.15
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        --order=random

  - label: 'iOS 14 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--resilient"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[h-z].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 14 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--resilient"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[a-g].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
          - "--fail-fast"
          - "--exclude=features/[h-z].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 45
    agents:
      queue: opensource
    plugins:
      artifacts#v1.3.0:
        download: ["features/fixtures/ios/output/iOSTestApp.ipa"]
      docker-compose#v3.3.0:
        run: cocoa-maze-runner
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
          - "--fail-fast"
          - "--exclude=features/[a-g].*.feature"
          - "--order=random"
    concurrency: 9
    concurrency_group: browserstack-app
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
