env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 15
    agents:
      queue: macos-14
    env:
      XCODE_VERSION: 15.3.0
    artifact_paths:
      - features/fixtures/macos/output/macOSTestApp_Release.zip
      - features/fixtures/macos/output/macOSTestApp_Debug.zip
    commands:
      - bundle install
      - make test-fixtures

  - label: 'ARM macOS 14 E2E tests 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: macos-14-
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/app_and_device_attributes.feature
        --os=macos
        --fail-fast

  - label: 'ARM macOS 14 E2E tests 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: macos-14-2
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/app_and_device_attributes.feature
        --os=macos
        --fail-fast

  - label: 'ARM macOS 14 E2E tests 3'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: macos-14-3
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/app_and_device_attributes.feature
        --os=macos
        --fail-fast

  - label: 'ARM macOS 14 E2E tests 4'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: macos-14-4
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/app_and_device_attributes.feature
        --os=macos
        --fail-fast

  - label: 'ARM macOS 14 E2E tests 5'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: macos-14-5
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/app_and_device_attributes.feature
        --os=macos
        --fail-fast

  - label: 'ARM macOS 14 E2E tests 6'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: macos-14-6
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/app_and_device_attributes.feature
        --os=macos
        --fail-fast

