env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # E2E tests
  #

  #
  # BitBar
  #
  - label: ':bitbar: iOS 15 E2E tests batch 1'
    depends_on: "cocoa_fixture"
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/iOSTestApp.ipa"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--exclude=features/[e-z].*.feature$"
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: iOS 15 E2E tests batch 2'
    depends_on: "cocoa_fixture"
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/iOSTestApp.ipa"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--exclude=features/[a-d].*.feature$"
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: ':bitbar: iOS 14 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/iOSTestApp.ipa"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bb"
          - "--device=IOS_14"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
          - "--order=random"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 14 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/iOSTestApp.ipa"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bb"
          - "--device=IOS_14"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[a-d].*.feature$"
          - "--order=random"
    concurrency: 25
    concurrency_group: 'bitbar-app'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  #
  # BrowserStack
  #
  - label: ':browserstack: iOS 13 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_13"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':browserstack: iOS 13 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_13"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[a-d].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':browserstack: iOS 12 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_12"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':browserstack: iOS 12 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_12"
          - "--appium-version=1.17.0"
          - "--fail-fast"
          - "--exclude=features/[a-d].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':browserstack: iOS 11 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    # More time than other steps as the BrowserStack iOS 11 devices seem particularly unstable and
    # sessions need resetting frequently, taking a minute or more each time.
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner-legacy
        run: cocoa-maze-runner-legacy
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_8_PLUS"
          - "--appium-version=1.8.0"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':browserstack: iOS 11 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    # More time than other steps as the BrowserStack iOS 11 devices seem particularly unstable and
    # sessions need resetting frequently, taking a minute or more each time.
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner-legacy
        run: cocoa-maze-runner-legacy
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_11_0_IPHONE_8_PLUS"
          - "--appium-version=1.8.0"
          - "--fail-fast"
          - "--exclude=features/[a-d].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'macOS 11 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: macos-11
    plugins:
      artifacts#v1.5.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "maze_output/failed/**/*"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --os=macos
        --fail-fast
        --order=random

  - label: 'ARM macOS 12 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: macos-12-arm
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
    commands:
      - bundle config set --local path 'vendor/bundle'
      - bundle install
      - bundle exec maze-runner
        --os=macos
        --fail-fast
        --order=random

  - label: 'macOS 10.13 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa-10.13
    plugins:
      artifacts#v1.5.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "maze_output/failed/**/*"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --os=macos
        --fail-fast
        --order=random

  - label: 'macOS 10.14 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa-10.14
    plugins:
      artifacts#v1.5.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "maze_output/failed/**/*"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --os=macos
        --fail-fast
        --order=random

  ##############################################################################
  #
  # Build example apps
  #

  - label: 'examples/objective-c-ios'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    commands:
      - cd examples/objective-c-ios
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-ios.xcworkspace -scheme objective-c-ios -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-ios.xcworkspace -scheme objective-c-ios -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug Mac Catalyst"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-ios.xcworkspace -scheme objective-c-ios -configuration Debug -destination generic/platform=macOS -derivedDataPath DerivedData -quiet build

  - label: 'examples/objective-c-osx'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    commands:
      - cd examples/objective-c-osx
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Release -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Debug -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swift-ios'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    commands:
      - cd examples/swift-ios
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -workspace swift-ios.xcworkspace -scheme swift-ios -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -workspace swift-ios.xcworkspace -scheme swift-ios -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swift-package-manager'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    commands:
      - cd examples/swift-package-manager
      - echo "--- Resolve Swift Package Dependencies"
      - sed -i '' -e 's/kind = branch/kind = revision/' -e "s/branch = master/revision = ${BUILDKITE_COMMIT}/" swift-package-manager.xcodeproj/project.pbxproj
      - xcodebuild -allowProvisioningUpdates -scheme swift-package-manager -derivedDataPath DerivedData -resolvePackageDependencies
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -scheme swift-package-manager -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -scheme swift-package-manager -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES

  - label: 'examples/swiftui'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    commands:
      - cd examples/swiftui
      - echo "--- Resolve Swift Package Dependencies"
      - sed -i '' -e 's/kind = branch/kind = revision/' -e "s/branch = master/revision = ${BUILDKITE_COMMIT}/" swiftui.xcodeproj/project.pbxproj
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (iOS)" -derivedDataPath DerivedData -resolvePackageDependencies
      - echo "+++ Build Release iOS"
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (iOS)" -configuration Release -destination generic/platform=iOS -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (iOS)" -configuration Debug -destination generic/platform=iOS\ Simulator -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Release macOS"
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (macOS)" -configuration Release -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Release tvOS"
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (tvOS)" -configuration Release -destination generic/platform=tvOS -derivedDataPath DerivedData -allowProvisioningUpdates -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug tvOS Simulator"
      - xcodebuild -allowProvisioningUpdates -scheme "swiftui (tvOS)" -configuration Debug -destination generic/platform=tvOS\ Simulator -derivedDataPath DerivedData -allowProvisioningUpdates -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
