env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Unit tests
  #

  - label: macOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: macOS 10.14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.14
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*

  - label: iOS 14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=14.5
    artifact_paths:
      - logs/*

  - label: iOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=11.4
    artifact_paths:
      - logs/*

  - label: iOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.15
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=10.3.1 DEVICE=iPhone\ 5s
    artifact_paths:
      - logs/*

  - label: tvOS 14 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-arm-mac-cocoa-12
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=14.5
    artifact_paths:
      - logs/*

  - label: tvOS 11 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-11
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=11.4
    artifact_paths:
      - logs/*

  - label: tvOS 10 unit tests
    timeout_in_minutes: 10
    agents:
      queue: opensource-mac-cocoa-10.15
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=tvOS OS=10.2
    artifact_paths:
      - logs/*

  ##############################################################################
  #
  # E2E tests
  #

  - label: 'macOS 10.15 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource-mac-cocoa-10.15
    plugins:
      artifacts#v1.5.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "maze_output/failed/**/*"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --os=macos
        --os-version=10.15
        --app=macOSTestApp
        --fail-fast
        --order=random

  - label: 'iOS 15 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_15"
          - "--appium-version=1.21.0"
          - "--fail-fast"
          - "--exclude=features/[h-z].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 15 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_15"
          - "--appium-version=1.21.0"
          - "--fail-fast"
          - "--exclude=features/[a-g].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
          - "--capabilities={\"browserstack.networkLogs\":\"true\"}"
          - "--exclude=features/[h-z].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: 'iOS 10 E2E tests batch 2'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/ios/output/ipa_url.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@build/ipa_url.txt"
          - "--farm=bs"
          - "--device=IOS_10"
          - "--appium-version=1.8.0"
          - "--exclude=features/[a-g].*.feature$"
          - "--order=random"
    concurrency: 24
    concurrency_group: browserstack-app
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
