name: "Pull Request"
on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Build framework
        # Base branch may not have the latest Makefile, so cannot use `make` here
        run: |
          xcodebuild -project Bugsnag.xcodeproj -configuration Release -scheme Bugsnag-iOS -destination generic/platform=iOS -derivedDataPath DerivedData -quiet clean build VALID_ARCHS=arm64
          eval $(stat -s DerivedData/Build/Products/Release-iphoneos/Bugsnag.framework/Bugsnag)
          echo $st_size > .size_before
          rm -rf DerivedData

      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          clean: false

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build framework
        run: |
          make compile_commands.json
          eval $(stat -s DerivedData/Build/Products/Release-iphoneos/Bugsnag.framework/Bugsnag)
          echo $st_size > .size_after
      
      - name: Infer
        run: make infer
      
      - name: OCLint
        run: make oclint

      - name: Danger
        run: bundle exec danger
        env:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
