name: "Pull Request"
on: [pull_request]
permissions: read-all

jobs:

  analyze:
    permissions:
      statuses: write
    runs-on: macos-14
    env:
      # Infer 1.0.1 cannot parse the iOS 15 SDK headers
      DEVELOPER_DIR: /Applications/Xcode_15.4.app
    steps:
    - name: Checkout pull request HEAD
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: brew install oclint && gem install xcpretty
    - name: Build framework
      run: make compile_commands.json
    - name: OCLint
      run: make oclint

  danger:
    permissions:
      pull-requests: write
      statuses: write
    runs-on: macos-14
    steps:
    - name: Checkout target branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.base_ref }}
    - name: Build framework
      run: xcodebuild -project Bugsnag.xcodeproj -configuration Release -target Bugsnag-iOS -destination generic/platform=iOS -quiet clean build VALID_ARCHS=arm64 RUN_CLANG_STATIC_ANALYZER=NO && mv build build.base
    - name: Checkout pull request merge branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        clean: false
        fetch-depth: 100
    - name: Build framework
      run: xcodebuild -project Bugsnag.xcodeproj -configuration Release -target Bugsnag-iOS -destination generic/platform=iOS -quiet clean build VALID_ARCHS=arm64 RUN_CLANG_STATIC_ANALYZER=NO
    - name: Install dependencies
      run: brew install bloaty && gem install danger
    - name: Run bloaty (compileunits)
      run: bloaty build/Release-iphoneos/Bugsnag.framework/Bugsnag --debug-file=build/Release-iphoneos/Bugsnag.framework.dSYM/Contents/Resources/DWARF/Bugsnag -n 0 -d compileunits
    - name: Run bloaty (sections,compileunits)
      run: bloaty build/Release-iphoneos/Bugsnag.framework/Bugsnag --debug-file=build/Release-iphoneos/Bugsnag.framework.dSYM/Contents/Resources/DWARF/Bugsnag -n 0 -d sections,compileunits
    - name: Run bloaty (sections,symbols)
      run: bloaty build/Release-iphoneos/Bugsnag.framework/Bugsnag --debug-file=build/Release-iphoneos/Bugsnag.framework.dSYM/Contents/Resources/DWARF/Bugsnag -n 0 -d sections,symbols
    - name: Run bloaty (segments,sections)
      run: bloaty build/Release-iphoneos/Bugsnag.framework/Bugsnag --debug-file=build/Release-iphoneos/Bugsnag.framework.dSYM/Contents/Resources/DWARF/Bugsnag -n 0 -d segments,sections
    - name: Run danger
      run: danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
