name: "Update Docs"
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout bugsnag-cocoa
        uses: actions/checkout@v2

      - name: Checkout docs branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs

      - name: Configure docs branch
        working-directory: docs
        run: |
          git config user.name "Bugsnag Bot"
          git config user.email notifiers@bugsnag.com

      - name: Update docs
        run: make docs

      - name: Push changes
        working-directory: docs
        run: |
          git status
          git push
