name: "Update Docs"
on:
  release:
    types: [published]
permissions: read-all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout bugsnag-cocoa
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Checkout docs branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: gh-pages
          path: docs

      - name: Configure docs branch
        working-directory: docs
        run: |
          git config user.name "Bugsnag Bot"
          git config user.email notifiers@bugsnag.com

      - name: Update docs
        run: make docs

      - name: Push changes
        working-directory: docs
        run: |
          git status
          git push
